version: "3"

services:
 
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
  
  drupal:
    build:
      context: .
      dockerfile: ./php-dockerfile
    container_name: drupal
    depends_on:
      - mariadb
    restart: unless-stopped
    volumes:
      - drupal-data:/var/www/html
  
  webserver:
    image: nginx:1.17.4-alpine
    container_name: webserver
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - drupal-data:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
  
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      ports:
          - 8081:80
      env_file: .env
      depends_on:
          - mariadb

volumes:
  drupal-data:
  db-data:
  
      
  
  
